# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'VCRH_MENU.ui'
##
## Created by: Qt User Interface Compiler version 6.1.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

    my_self.actionExit = QAction(my_self)
    my_self.actionExit.setObjectName(u"actionExit")
    my_self.actionLogout = QAction(my_self)
    my_self.actionLogout.setObjectName(u"actionLogout")
    my_self.actionAnalysis_Sections = QAction(my_self)
    my_self.actionAnalysis_Sections.setObjectName(u"actionAnalysis_Sections")
    my_self.actionConstruction_Rehab_History = QAction(my_self)
    my_self.actionConstruction_Rehab_History.setObjectName(u"actionConstruction_Rehab_History")
    my_self.actionConst_Rehab_Layer_Detail = QAction(my_self)
    my_self.actionConst_Rehab_Layer_Detail.setObjectName(u"actionConst_Rehab_Layer_Detail")
    my_self.actionProject = QAction(my_self)
    my_self.actionProject.setObjectName(u"actionProject")
    my_self.actionAbout = QAction(my_self)
    my_self.actionAbout.setObjectName(u"actionAbout")
    my_self.actionUpdate = QAction(my_self)
    my_self.actionUpdate.setObjectName(u"actionUpdate")
    my_self.actionDelete = QAction(my_self)
    my_self.actionDelete.setObjectName(u"actionDelete")
    my_self.actionsplit = QAction(my_self)
    my_self.actionsplit.setObjectName(u"actionsplit")
    my_self.actionShift = QAction(my_self)
    my_self.actionShift.setObjectName(u"actionShift")
    my_self.actionMerge = QAction(my_self)
    my_self.actionMerge.setObjectName(u"actionMerge")
    my_self.actionAdjust = QAction(my_self)
    my_self.actionAdjust.setObjectName(u"actionAdjust")
    my_self.actionCopy = QAction(my_self)
    my_self.actionCopy.setObjectName(u"actionCopy")
    my_self.actionContents = QAction(my_self)
    my_self.actionContents.setObjectName(u"actionContents")
    my_self.actionPaste = QAction(my_self)
    my_self.actionPaste.setObjectName(u"actionPaste")
    my_self.actionTo_Section = QAction(my_self)
    my_self.actionTo_Section.setObjectName(u"actionTo_Section")
    my_self.actionTo_Road = QAction(my_self)
    my_self.actionTo_Road.setObjectName(u"actionTo_Road")

    
    my_self.menubar = QMenuBar(my_self)
    my_self.menubar.setObjectName(u"menubar")
    my_self.menubar.setGeometry(QRect(0, 0, 1253, 22))
    my_self.menuFile = QMenu(my_self.menubar)
    my_self.menuFile.setObjectName(u"menuFile")
    my_self.menuView = QMenu(my_self.menubar)
    my_self.menuView.setObjectName(u"menuView")
    my_self.menuHelp = QMenu(my_self.menubar)
    my_self.menuHelp.setObjectName(u"menuHelp")
    my_self.menuEdit = QMenu(my_self.menubar)
    my_self.menuEdit.setObjectName(u"menuEdit")
    my_self.menuAdd = QMenu(my_self.menuEdit)
    my_self.menuAdd.setObjectName(u"menuAdd")
    my_self.setMenuBar(my_self.menubar)
   
    my_self.statusBar = QStatusBar(my_self)
    my_self.statusBar.setObjectName(u"statusBar")
    my_self.setStatusBar(my_self.statusBar)

    my_self.menubar.addAction(my_self.menuFile.menuAction())
    my_self.menubar.addAction(my_self.menuView.menuAction())
    my_self.menubar.addAction(my_self.menuEdit.menuAction())
    my_self.menubar.addAction(my_self.menuHelp.menuAction())
    my_self.menuFile.addAction(my_self.actionLogout)
    my_self.menuFile.addSeparator()
    my_self.menuFile.addAction(my_self.actionExit)
    my_self.menuView.addAction(my_self.actionAnalysis_Sections)
    my_self.menuView.addAction(my_self.actionConstruction_Rehab_History)
    my_self.menuView.addAction(my_self.actionConst_Rehab_Layer_Detail)
    my_self.menuView.addAction(my_self.actionProject)
    my_self.menuHelp.addAction(my_self.actionContents)
    my_self.menuHelp.addSeparator()
    my_self.menuHelp.addAction(my_self.actionAbout)
    my_self.menuEdit.addAction(my_self.menuAdd.menuAction())
    my_self.menuEdit.addAction(my_self.actionUpdate)
    my_self.menuEdit.addAction(my_self.actionCopy)
    my_self.menuEdit.addAction(my_self.actionPaste)
    my_self.menuEdit.addAction(my_self.actionDelete)
    my_self.menuEdit.addSeparator()
    my_self.menuEdit.addAction(my_self.actionMerge)
    my_self.menuAdd.addAction(my_self.actionTo_Section)
    my_self.menuAdd.addAction(my_self.actionTo_Road)
    
    my_self.actionExit.triggered.connect(my_self.close)
        
    my_self.setWindowTitle(QCoreApplication.translate("MainWindow", u"PVMT_SNAP editor", None))
    my_self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
    my_self.actionLogout.setText(QCoreApplication.translate("MainWindow", u"Logout", None))
    my_self.actionAnalysis_Sections.setText(QCoreApplication.translate("MainWindow", u"Analysis Sections", None))
    my_self.actionConstruction_Rehab_History.setText(QCoreApplication.translate("MainWindow", u"Construction Rehab History", None))
    my_self.actionConst_Rehab_Layer_Detail.setText(QCoreApplication.translate("MainWindow", u"Const Rehab Layer Detail", None))
    my_self.actionProject.setText(QCoreApplication.translate("MainWindow", u"Project", None))
    my_self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
    my_self.actionUpdate.setText(QCoreApplication.translate("MainWindow", u"Update", None))
#if QT_CONFIG(tooltip)
    my_self.actionUpdate.setToolTip(QCoreApplication.translate("MainWindow", u"Update Existing Section Data", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
    my_self.actionUpdate.setStatusTip(QCoreApplication.translate("MainWindow", u"Update Existing Section Data", None))
#endif // QT_CONFIG(statustip)
    my_self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
    my_self.actionsplit.setText(QCoreApplication.translate("MainWindow", u"Split", None))
    my_self.actionShift.setText(QCoreApplication.translate("MainWindow", u"Shift", None))
    my_self.actionMerge.setText(QCoreApplication.translate("MainWindow", u"Merge", None))
#if QT_CONFIG(tooltip)
    my_self.actionMerge.setToolTip(QCoreApplication.translate("MainWindow", u"Merge Two Sections", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
    my_self.actionMerge.setStatusTip(QCoreApplication.translate("MainWindow", u"Merge Two Sections", None))
#endif // QT_CONFIG(statustip)
    my_self.actionAdjust.setText(QCoreApplication.translate("MainWindow", u"Adjust", None))
    my_self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(tooltip)
    my_self.actionCopy.setToolTip(QCoreApplication.translate("MainWindow", u" Copy Project  Data from a Section", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
    my_self.actionCopy.setStatusTip(QCoreApplication.translate("MainWindow", u"Copy Project Data From a Section", None))
#endif // QT_CONFIG(statustip)
    my_self.actionContents.setText(QCoreApplication.translate("MainWindow", u"Contents", None))
    my_self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(tooltip)
    my_self.actionPaste.setToolTip(QCoreApplication.translate("MainWindow", u"Paste Project Data to a Section", None))
#endif // QT_CONFIG(tooltip)
    my_self.actionTo_Section.setText(QCoreApplication.translate("MainWindow", u"To Section", None))
    my_self.actionTo_Road.setText(QCoreApplication.translate("MainWindow", u"To Road", None))
    my_self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
    my_self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    my_self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
    my_self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
    my_self.menuAdd.setTitle(QCoreApplication.translate("MainWindow", u"Add", None))
   
    

